import type { Metadata } from "next";
import "../globals.css";
import "../main.scss";

import { AntdRegistry } from "@ant-design/nextjs-registry";
import React from "react";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { inter } from "./fonts";
import Navbar from "@/modules/shared/layouts/navbar/navbar";
import { ConfigProvider } from "antd";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const LocaleLayout = async ({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) => {
  const messages = await getMessages();
  // Define RTL languages
  const rtlLanguages = ["ar", "fa", "he"];
  const dir = rtlLanguages.includes(locale) ? "rtl" : "ltr";

  return (
    <html lang={locale} dir={dir}>
      <body className={inter.className}>
        <Providers>
          <ConfigProvider direction={dir}>
            <NextIntlClientProvider messages={messages}>
              <Navbar />
              <AntdRegistry>{children}</AntdRegistry>
            </NextIntlClientProvider>
          </ConfigProvider>
        </Providers>
      </body>
    </html>
  );
};
export default LocaleLayout;
